windowrulev2 = float, class:(sound.sound)
windowrulev2 = float, class:(sound.music)
windowrulev2 = float, class:(files.files)
windowrulev2 = float, class:(thunar)
windowrulev2 = float, class:(update.upgrade)
windowrulev2 = float, class:(system.net)
windowrulev2 = float, class:(system.blue)
windowrulev2 = float, class:(system.stat)
windowrulev2 = float, class:(term.float)

windowrulev2 = size 900 600, class:(sound.sound)
windowrulev2 = size 900 600, class:(sound.music)
windowrulev2 = size 900 600, class:(files.files)
windowrulev2 = size 900 600, class:(thunar)
windowrulev2 = size 900 600, class:(update.upgrade)
windowrulev2 = size 900 600, class:(system.net)
windowrulev2 = size 900 600, class:(system.blue)
windowrulev2 = size 1000 700, class:(system.stat)
windowrulev2 = size 1000 700, class:(term.float)
#XWayland
windowrulev2 = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrulev2 = noanim, class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus, class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrulev2 = noblur, class:^(xwaylandvideobridge)$
windowrulev2 = nofocus, class:^(xwaylandvideobridge)$
