#!/bin/bash

systemctl --user stop wayland-wm-app-daemon.service
systemctl --user start wayland-wm-app-daemon.service
systemctl --user stop pipewire.service wireplumber.service pipewire.socket pipewire-pulse.service pipewire-pulse.socket
systemctl --user start pipewire.service wireplumber.service pipewire.socket pipewire-pulse.service pipewire-pulse.socket
systemctl --user stop xdg-desktop-portal.service
systemctl --user start xdg-desktop-portal.service
systemctl --user stop xdg-desktop-portal-gtk.service
systemctl --user start xdg-desktop-portal-gtk.service
systemctl --user stop xdg-desktop-portal-xapp.service
systemctl --user start xdg-desktop-portal-xapp.service
systemctl --user stop xdg-desktop-portal-hyprland.service
systemctl --user start xdg-desktop-portal-hyprland.service
systemctl --user stop hyprpolkitagent.service
systemctl --user start hyprpolkitagent.service
systemctl --user stop hyprpaper.service
systemctl --user start hyprpaper.service
systemctl --user stop hypridle.service
systemctl --user start hypridle.service
