#!/bin/bash
iDIR="$HOME/.config/swaync/icons"
sDIR="$HOME/.config/hypr/scripts"
volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}')
mute_status_speaker=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q "[MUTED]" && echo "true" || echo "false")
mic_volume=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | awk '{print $2}')
mute_status_mic=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -q "[MUTED]" && echo "true" || echo "false")

# Get Volume
get_volume() {
if [ "$(echo "$volume == 0.00" | bc)" -eq 1 ]; then
     echo "Silent"
 else
           echo "$(echo "$volume * 100" | bc -l | awk '{printf "%.0f", $1}') %"
 fi
}

# Get Mic Volume
get_mic_volume() {
if [ "$(echo "$mic_volume == 0.00" | bc)" -eq 1 ]; then
     echo "Muted"
 else
           echo "$(echo "$mic_volume * 100" | bc -l | awk '{printf "%.0f", $1}') %"
 fi
}

# Get icons
get_icon() {
    current=$(get_volume)
    volume_percent=$(echo "$volume * 100" | bc -l | awk '{printf "%.0f", $1}')
    if [[ "$current" == "Silent" ]]; then
        echo "$iDIR/volume-mute.png"
    elif (( $(echo "$volume_percent <= 30" | bc -l) )); then
        echo "$iDIR/volume-low.png"
    elif (( $(echo "$volume_percent <= 60" | bc -l) )); then
        echo "$iDIR/volume-mid.png"
    else
        echo "$iDIR/volume-high.png"
    fi
}

# Notify
notify_user() {
    if [[ "$(get_volume)" == "Muted" ]]; then
        notify-send -e -h string:x-canonical-private-synchronous:volume_notif -u low -i "$(get_icon)" " Volume:" " Muted"
    else
        notify-send -e -h int:value:"$(get_volume | sed 's/%//')" -h string:x-canonical-private-synchronous:volume_notif -u low -i "$(get_icon)" " Volume Level:" " $(get_volume)" &&
        "$sDIR/sounds" --volume
    fi
}

# Increase Volume
inc_volume() {
    if [ "$mute_status_speaker" == "true" ]; then
      toggle_mute
    else
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && notify_user
    fi
}

# Decrease Volume
dec_volume() {
    if [ "$mute_status_speaker" == "true" ]; then
        toggle_mute
    else
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify_user
    fi
}

# Toggle Mute
toggle_mute() {
	if [ "$mute_status_speaker" == "false" ]; then
		 wpctl set-mute @DEFAULT_AUDIO_SINK@ 1 && notify-send -e -u low -i "$iDIR/volume-mute.png" " Volume:" " Switched OFF"
	elif [ "$mute_status_speaker" == "true" ]; then
  wpctl set-mute @DEFAULT_AUDIO_SINK@ 0 && notify-send -e -u low -i "$(get_icon)" " Volume:" " Switched ON"
	fi
}

# Toggle Mic
toggle_mic() {
	if [ "$mute_status_mic" == "false" ]; then
		wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 1 && notify-send -e -u low -i "$iDIR/microphone-mute.png" " Microphone:" " Switched OFF"
	elif [ "$mute_status_mic" == "true" ]; then
		 wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 0 && notify-send -e -u low -i "$iDIR/microphone.png" " Microphone:" " Switched ON"
	fi
}
# Get Mic Icon
get_mic_icon() {
    current=$(get_mic_volume)
    mic_percent=$(echo "$mic_volume * 100" | bc -l | awk '{printf "%.0f", $1}')
    if [[ "$current" == "Muted" ]]; then
        echo "$iDIR/microphone-mute.png"
    else
        echo "$iDIR/microphone.png"
    fi
}

# Notify for Microphone
notify_mic_user() {
    volume=$(get_mic_volume)
    icon=$(get_mic_icon)
    notify-send -e -h int:value:"$volume" -h "string:x-canonical-private-synchronous:volume_notif" -u low -i "$icon"  " Mic Level:" " $volume"
}

# Increase MIC Volume
inc_mic_volume() {
    if [ "$mute_status_mic" = "true" ]; then
        toggle_mic
    else
      wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%+ && notify_mic_user
    fi
}

# Decrease MIC Volume
dec_mic_volume() {
    if [ "$mute_status_mic" = "true" ]; then
        toggle-mic
    else
      wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%- && notify_mic_user
    fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
	get_icon
elif [[ "$1" == "--get-mic-icon" ]]; then
	get_mic_icon
elif [[ "$1" == "--mic-inc" ]]; then
	inc_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
	dec_mic_volume
else
	get_volume
fi
