#settings
source = $XDG_CONFIG_HOME/hypr/settings/theme.conf
source = $XDG_CONFIG_HOME/hypr/settings/binds.conf
source = $XDG_CONFIG_HOME/hypr/settings/cursor.conf
source = $XDG_CONFIG_HOME/hypr/settings/debug.conf
source = $XDG_CONFIG_HOME/hypr/settings/gestures.conf
source = $XDG_CONFIG_HOME/hypr/settings/input.conf
source = $XDG_CONFIG_HOME/hypr/settings/misc.conf
source = $XDG_CONFIG_HOME/hypr/settings/extra.conf
source = $XDG_CONFIG_HOME/hypr/settings/monitors.conf
source = $XDG_CONFIG_HOME/hypr/settings/workspaces.conf

#autostart
source = $XDG_CONFIG_HOME/hypr/autostart/autostart.conf
source = $XDG_CONFIG_HOME/hypr/autostart/environmental.conf

#keybinds
source = $XDG_CONFIG_HOME/hypr/keybinds/keybinds.conf

source = $XDG_CONFIG_HOME/hypr/plugins/hyprfocus.conf
