format = """
$time\
$os\
$shell\
$username\
$hostname\
[ ](fg:#1d1e2a bg:#3b4261)\
$directory\
[ ](fg:#1d1e2a bg:#3b4261)\
$git_status\
[ ](fg:#1d1e2a bg:#00000000)\
$battery\
\n$character"""

[character]
success_symbol = '[ 󱞩](bold green) '
error_symbol = '[ 󱞩 ](bold red) '
vimcmd_symbol = '[ 󱞩 ](bold green) '

[os]
format = '[ $symbol]($style)'
style = "bg:#1d1e2a fg:bold blue"
disabled = false

[os.symbols]
Android = " "
Arch = "󰣇 "
Debian = " "
Fedora = " "
Kali = " "
NixOS = "󱄅 "
Nobara = " "
Ubuntu = " "
Windows = " "

[username]
style_user = 'bg:#1d1e2a fg:bold blue'
style_root = 'bg:#1d1e2a fg:bold blue'
format = '[$user]($style)'
disabled = false
show_always = true
aliases = { "corpuser034g" = "matchai" }

[hostname]
ssh_only = false
format = '[@$hostname$ssh_symbol ]($style)'
style = "bg:#1d1e2a fg:bold blue"
disabled = false
ssh_symbol = " "

[directory]
format = '[$path]($style)'
style =  "fg:#c3e88d bg:#3b4261"
disabled = false
home_symbol = ""
use_os_path_sep = true
truncation_symbol = ".../"
truncate_to_repo = true
truncation_length = 3

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Desktop" = ""
"Public" = ""
"Templates" = ""
"Videos" = "󰕧"
".config" = ""
".local" = "󰜞"
"share" = ""
".cache" = "󰃨"
".var" = ""
"mnt" = "󰉉"
"container" = ""
"libvirt" = "󱄔"
"media" = ""
"projects" = ""
"rclone" = ""
"raid0" = ""
"hyprland" = ""
"hypr" = ""
"nvim" = ""
"isos" = "󰻂"
"vms" = "󰒋"

[git_status]
"format" = '([ \[$all_status$ahead_behind\] ]($style))'
"style" = 'fg:#bb9af7 bg:#1d1e2a'
"conflicted" = '='
"ahead" = '⇡'
"behind" = '⇣'
"diverged" = '⇕'
"up_to_date" = ''
"untracked" = '?'
"stashed" = '$'
"modified" = '!'
"staged" = '+'
"renamed" = '»'
"deleted" = ''

[time]
format = '[  $time ]($style)'
"time_format" = '%T'
"style" = 'fg:#c0caf5 bg:#1d1e2a'
"utc_time_offset" = 'local'
"disabled" = false

[battery]
full_symbol = '󰁹'
charging_symbol = '󰂄'
"empty_symbol" = '󰂎'
"discharging_symbol" = '󰂃'
"format" = '[$symbol$percentage]($style) '
style = 'fg:#4fd6be'
[[battery.display]] 
threshold = 90
"discharging_symbol" = '󰂂'
[[battery.display]] 
threshold = 80
style = '#4fd6be'
"discharging_symbol" = '󰂁'
[[battery.display]] 
threshold = 70
style = '#4fd6be'
"discharging_symbol" = '󰂀'
[[battery.display]] 
threshold = 60
style = 'fg:#ffc777'
"discharging_symbol" = '󰁿'
[[battery.display]] 
threshold = 50
style = 'fg:#ffc777'
"discharging_symbol" = '󰁾'
[[battery.display]] 
threshold = 40
style = 'fg:#ffc777'
"discharging_symbol" = '󰁽'
[[battery.display]] 
threshold = 30
style = 'fg:#ff007c'
"discharging_symbol" = '󰁼'
[[battery.display]] 
threshold = 20
style = 'fg:#ff007c'
"discharging_symbol" = '󰁻'
[[battery.display]] 
threshold = 10
style = 'fg:#ff007c'
"discharging_symbol" = '󰁺'
